# Project: WordSearchPuzzle
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainWSP.o display.o leaderboard.o node.o wordSearch.o
LINKOBJ  = mainWSP.o display.o leaderboard.o node.o wordSearch.o
LIBS     = -L"C:/Users/USER/DevC/Dev-Cpp/MinGW64/lib" -L"C:/Users/USER/DevC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/include" -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/include" -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/USER/DevC/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = WordSearchPuzzle.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainWSP.o: mainWSP.cpp
	$(CPP) -c mainWSP.cpp -o mainWSP.o $(CXXFLAGS)

display.o: display.cpp
	$(CPP) -c display.cpp -o display.o $(CXXFLAGS)

leaderboard.o: leaderboard.cpp
	$(CPP) -c leaderboard.cpp -o leaderboard.o $(CXXFLAGS)

node.o: node.cpp
	$(CPP) -c node.cpp -o node.o $(CXXFLAGS)

wordSearch.o: wordSearch.cpp
	$(CPP) -c wordSearch.cpp -o wordSearch.o $(CXXFLAGS)
